# Generated by Django 6.1 on 2026-09-02 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule_candidat', models.CharField(editable=False, max_length=30, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenoms', models.CharField(max_length=150)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=150)),
                ('nationalite', models.CharField(default='Ivoirienne', max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='candidats/photos/')),
                ('telephone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('dernier_diplome', models.CharField(blank=True, max_length=150)),
                ('serie_diplome', models.CharField(blank=True, max_length=100)),
                ('annee_obtention', models.PositiveIntegerField(blank=True, null=True)),
                ('etablissement_origine', models.CharField(blank=True, max_length=200)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Candidat',
                'verbose_name_plural': 'Candidats',
                'ordering': ['nom', 'prenoms'],
            },
        ),
        migrations.CreateModel(
            name='Preinscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=30, unique=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('DOSSIER_INCOMPLET', 'Dossier incomplet'), ('DOSSIER_COMPLET', 'Dossier complet'), ('VALIDEE', 'Validée'), ('REJETEE', 'Rejetée')], default='EN_ATTENTE', max_length=30)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('observation', models.TextField(blank=True)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preinscriptions', to='gestion.anneeacademique')),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preinscriptions', to='gestion.candidat')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preinscriptions', to='gestion.filiere')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preinscriptions', to='gestion.niveau')),
            ],
            options={
                'verbose_name': 'Préinscription',
                'verbose_name_plural': 'Préinscriptions',
                'ordering': ['-date_demande'],
                'constraints': [models.UniqueConstraint(fields=('candidat', 'annee_academique'), name='unique_preinscription_candidat_annee')],
            },
        ),
    ]
