# Generated by Django 6.1 on 2026-09-02 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_candidat_preinscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(editable=False, max_length=30, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
                ('candidat', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='etudiant', to='gestion.candidat')),
            ],
            options={
                'verbose_name': 'Étudiant',
                'verbose_name_plural': 'Étudiants',
                'ordering': ['matricule'],
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=30, unique=True)),
                ('type_inscription', models.CharField(choices=[('PREMIERE_INSCRIPTION', 'Première inscription'), ('REINSCRIPTION', 'Réinscription')], default='PREMIERE_INSCRIPTION', max_length=30)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('INSCRIT', 'Inscrit'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=20)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('observation', models.TextField(blank=True)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions', to='gestion.anneeacademique')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions', to='gestion.classe')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions', to='gestion.etudiant')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions', to='gestion.filiere')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions', to='gestion.niveau')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'ordering': ['-date_inscription'],
                'constraints': [models.UniqueConstraint(fields=('etudiant', 'annee_academique'), name='unique_inscription_etudiant_annee')],
            },
        ),
    ]
