# Generated by Django 6.1 on 2026-09-02 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_etudiant_inscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scolarite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remise', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_net', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('reste_a_payer', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('statut', models.CharField(choices=[('NON_PAYEE', 'Non payée'), ('PARTIELLEMENT_PAYEE', 'Partiellement payée'), ('SOLDEE', 'Soldée')], default='NON_PAYEE', max_length=30)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('observation', models.TextField(blank=True)),
                ('inscription', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='scolarite', to='gestion.inscription')),
            ],
            options={
                'verbose_name': 'Scolarité',
                'verbose_name_plural': 'Scolarités',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Echeance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('libelle', models.CharField(max_length=150)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_echeance', models.DateField()),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('reste_a_payer', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('statut', models.CharField(choices=[('A_VENIR', 'À venir'), ('EN_COURS', 'En cours'), ('PAYEE', 'Payée'), ('EN_RETARD', 'En retard')], default='A_VENIR', max_length=20)),
                ('scolarite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='echeances', to='gestion.scolarite')),
            ],
            options={
                'verbose_name': 'Échéance',
                'verbose_name_plural': 'Échéances',
                'ordering': ['numero'],
                'constraints': [models.UniqueConstraint(fields=('scolarite', 'numero'), name='unique_echeance_scolarite_numero')],
            },
        ),
    ]
