# Generated by Django 6.1 on 2026-09-02 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_scolarite_echeance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=40, unique=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mode_paiement', models.CharField(choices=[('ESPECES', 'Espèces'), ('CHEQUE', 'Chèque'), ('VIREMENT', 'Virement bancaire'), ('MOBILE_MONEY', 'Mobile Money'), ('CARTE', 'Carte bancaire'), ('AUTRE', 'Autre')], max_length=30)),
                ('statut', models.CharField(choices=[('VALIDE', 'Validé'), ('ANNULE', 'Annulé')], default='VALIDE', max_length=20)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('observation', models.TextField(blank=True)),
                ('echeance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='gestion.echeance')),
                ('scolarite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='gestion.scolarite')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='Recu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=40, unique=True)),
                ('date_emission', models.DateTimeField(auto_now_add=True)),
                ('observation', models.TextField(blank=True)),
                ('paiement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='recu', to='gestion.paiement')),
            ],
            options={
                'verbose_name': 'Reçu',
                'verbose_name_plural': 'Reçus',
                'ordering': ['-date_emission'],
            },
        ),
    ]
