# Generated by Django 5.2.7 on 2026-09-07 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_paiement_recu'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='mode_paiement_inscription',
            field=models.CharField(choices=[('UNE_TRANCHE', 'Une seule tranche'), ('DEUX_TRANCHES', 'Deux tranches')], default='UNE_TRANCHE', max_length=20, verbose_name='Mode de paiement'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='montant_inscription',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name="Frais d'inscription"),
        ),
        migrations.CreateModel(
            name='EcheanceInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_tranche', models.CharField(choices=[('TRANCHE_1', 'Tranche 1'), ('TRANCHE_2', 'Tranche 2')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12)),
                ('montant_paye', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('NON_PAYEE', 'Non payée'), ('PARTIELLE', 'Partiellement payée'), ('PAYEE', 'Payée')], default='NON_PAYEE', max_length=20)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echeances', to='gestion.inscription')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
