# Generated by Django 5.2.7 on 2026-09-07 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_inscription_mode_paiement_inscription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=40, unique=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mode_paiement', models.CharField(choices=[('ESPECES', 'Espèces'), ('CHEQUE', 'Chèque'), ('VIREMENT', 'Virement bancaire'), ('MOBILE_MONEY', 'Mobile Money'), ('CARTE', 'Carte bancaire'), ('AUTRE', 'Autre')], max_length=30)),
                ('statut', models.CharField(choices=[('VALIDE', 'Validé'), ('ANNULE', 'Annulé')], default='VALIDE', max_length=20)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('observation', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': "Paiement des frais d'inscription",
                'verbose_name_plural': "Paiements des frais d'inscription",
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='RecuInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=40, unique=True)),
                ('date_emission', models.DateTimeField(auto_now_add=True)),
                ('observation', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': "Reçu des frais d'inscription",
                'verbose_name_plural': "Reçus des frais d'inscription",
                'ordering': ['-date_emission'],
            },
        ),
        migrations.AlterModelOptions(
            name='echeanceinscription',
            options={'ordering': ['id'], 'verbose_name': "Échéance d'inscription", 'verbose_name_plural': "Échéances d'inscription"},
        ),
        migrations.AlterField(
            model_name='echeanceinscription',
            name='inscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echeances_inscription', to='gestion.inscription'),
        ),
        migrations.AlterField(
            model_name='echeanceinscription',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='echeanceinscription',
            name='montant_paye',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AddConstraint(
            model_name='echeanceinscription',
            constraint=models.UniqueConstraint(fields=('inscription', 'type_tranche'), name='unique_echeance_inscription_tranche'),
        ),
        migrations.AddField(
            model_name='paiementinscription',
            name='echeance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='gestion.echeanceinscription'),
        ),
        migrations.AddField(
            model_name='paiementinscription',
            name='inscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements_inscription', to='gestion.inscription'),
        ),
        migrations.AddField(
            model_name='recuinscription',
            name='paiement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='recu', to='gestion.paiementinscription'),
        ),
    ]
