# Generated by Django 5.2.7 on 2026-09-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_paiementinscription_recuinscription_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='echeanceinscription',
            options={'ordering': ['id'], 'verbose_name': 'Échéance inscription', 'verbose_name_plural': 'Échéances inscription'},
        ),
        migrations.AlterField(
            model_name='echeanceinscription',
            name='montant',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='echeanceinscription',
            name='montant_paye',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
