# Generated by Django 5.2.7 on 2026-09-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_alter_echeanceinscription_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paiementinscription',
            options={'ordering': ['-date_paiement'], 'verbose_name': 'Paiement inscription', 'verbose_name_plural': 'Paiements inscription'},
        ),
        migrations.AlterModelOptions(
            name='recuinscription',
            options={'ordering': ['-date_emission'], 'verbose_name': 'Reçu inscription', 'verbose_name_plural': 'Reçus inscription'},
        ),
        migrations.AlterField(
            model_name='paiementinscription',
            name='montant',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
    ]
